name = "sciolism 2019"
license = "MIT"
licenselink = "https://github.com/chemiker/sciolism-2019/blob/master/LICENSE"
description = "sciolism 2019 is a light-weighted and minimalistic theme designed for blogs."
homepage = "http://example.com/"
tags = ["Fontawesome", "Font awesome", "Search", "Mobile", "White", "Clean", "Responsive", "Blog", "Accessibility"]
features = ["search", "mobile", "responsive", "accessibility"]
min_version = "0.48"

[author]
  name = "Alexander Lüken"
  homepage = "https://sciolism.de"
